### ISSUE TITLE
SparseGridTopology segmentation fault when the grid is out of bound

### ISSUE THREAD

**Issue by jnbrunet** [sofa-framework/sofa#1748] opened 2021-01-27 14:40 UTC
Bug reported by @AndreaMendizabal 

When a SparseGridTopology doesn't contain any embedded nodes within its boundaries (set using `min` and `max` data parameters), it simply crashes. 

Minimal reproducible example:
```xml
<Node>
    <Mesh name="m" position="0 0 0" />
    <SparseGridTopology min="0 0 1" max="1 1 1" src="@m" />
</Node>
```

Output:
```
########## SIG 11 - SIGSEGV: segfault ##########
-> /opt/sofa/lib/libSofaHelper.so.20.12.00(sofa::helper::BackTrace::dump()+0x23) [0x7f679f685cf3]
-> /opt/sofa/lib/libSofaHelper.so.20.12.00(sofa::helper::BackTrace::sig(int)+0x1cf) [0x7f679f68606f]
-> /lib64/libc.so.6(+0x3da60) [0x7f679ef35a60]
-> /opt/sofa/lib/libSofaBaseTopology.so.20.12.00(sofa::component::topology::SparseGridTopology::voxelizeTriangleMesh(sofa::helper::io::Mesh*, boost::intrusive_ptr<sofa::component::topology::RegularGridTopology>, sofa::helper::vector<sofa::component::topology::SparseGridTopology::Type, sofa::helper::CPUMemoryManager<sofa::component::topology::SparseGridTopology::Type> >&) const+0x1f2) [0x7f67a0b49082]
-> /opt/sofa/lib/libSofaBaseTopology.so.20.12.00(sofa::component::topology::SparseGridTopology::buildFromTriangleMesh(sofa::helper::io::Mesh*)+0x2c8) [0x7f67a0b4a3d8]
-> /opt/sofa/lib/libSofaBaseTopology.so.20.12.00(sofa::component::topology::SparseGridTopology::buildAsFinest()+0x2d8) [0x7f67a0b4ac58]
-> /opt/sofa/lib/libSofaBaseTopology.so.20.12.00(+0x2d2a2b) [0x7f67a0b3fa2b]
-> /opt/sofa/lib/libSofaSimulationCore.so.20.12.00(sofa::simulation::InitVisitor::processNodeTopDown(sofa::simulation::Node*)+0x1a3) [0x7f67a054e5b3]
-> /opt/sofa/lib/libSofaSimulationGraph.so.20.12.00(sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)+0x3a5) [0x7f67a5421455]
-> /opt/sofa/lib/libSofaSimulationGraph.so.20.12.00(sofa::simulation::graph::DAGNode::doExecuteVisitor(sofa::simulation::Visitor*, bool)+0x15f) [0x7f67a542187f]
-> /opt/sofa/lib/libSofaSimulationCore.so.20.12.00(sofa::simulation::Simulation::initNode(sofa::simulation::Node*)+0xaa) [0x7f67a05b8b4a]
-> /opt/sofa/lib/libSofaSimulationCore.so.20.12.00(sofa::simulation::Simulation::init(sofa::simulation::Node*)+0xb0) [0x7f67a05b8620]
-> runSofa() [0x40f3a3]
-> /lib64/libc.so.6(__libc_start_main+0xf2) [0x7f679ef201e2]
-> runSofa() [0x4105de]
[1]    36378 segmentation fault (core dumped)  runSofa /tmp/test.scn
```

**Comment by alxbilger** [comment] 2022-06-10 13:56
I am not able to reproduce this issue. I close it for now, but if you have time @jnbrunet and @AndreaMendizabal test it again and re-open the issue if necessary.

I tried to run the mentioned scene. Result: an error message without crash
```
[ERROR]   [SparseGridTopology(SparseGridTopology1)] vertex 0 not found in hexahedral topology
```

**Closed as completed by alxbilger** 2022-06-10 13:56 UTC
Labels: issue: good first issue, issue: bug (minor), STC#13
