### ISSUE TITLE
SparseGridTopology miss some point

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#1974] opened 2021-04-01 17:18 UTC
```
 <MeshObjLoader name="loader1" filename="mesh/cylinder-1.obj"/>
  <SparseGridTopology name="grid1" n="3 2 3" position="@loader1.position" drawHexahedra="1" />
  <OglModel name="Visual" src="@loader1"  />
```

This example is supposed to create 4 Hexa on top of the Camembert but only 3 are created... 
![image](https://user-images.githubusercontent.com/21199245/113330407-f98cfa80-931e-11eb-9b28-94651fcab4ed.png)

**Comment by fredroy** [comment] 2021-04-09 09:28
This is not really explaining the problem but it is better to give facets as well for the sparsegrid (to know if you are inside or outside the mesh)
if you do:
```xml
    <MeshObjLoader name="loader1" filename="mesh/cylinder-1.obj" translation="0 2 0"/>
    <SparseGridTopology name="grid1" n="4 2 4" src="@loader1" drawHexahedra="1" />
    <OglModel name="Visual" src="@loader1" />
```
it works:
<img src="https://user-images.githubusercontent.com/11028016/114159654-4c217480-9926-11eb-9929-473d207b923b.png" width="400" >

**Comment by fredroy** [comment] 2021-05-07 09:14
This issue will be closed as SparseGrid is working as intended (even if it is not really clear)
Excerpt [SparseGridTopology.h](https://github.com/sofa-framework/sofa/blob/c05ff12d4540a7b0f62052583f318090bfe91c31/SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/SparseGridTopology.h#L44) :
```
A sparse grid topology. Like a sparse FFD building from the bounding box of the object. Starting from a RegularGrid, only valid cells containing matter (ie intersecting the original surface mesh or totally inside the object) are considered.
 * Valid cells are tagged by a Type BOUNDARY or INSIDE
```
Closing.

**Closed as completed by fredroy** 2021-05-07 09:14 UTC
Labels: issue: bug (major)
