### ISSUE TITLE
[MeshVTKLoader] Bug in the scale parameter that is accepting "0,100" instead of "0.100"

### ISSUE THREAD

**Issue by GuillaumeULB** [sofa-framework/sofa#151] opened 2017-01-25 13:53 UTC
If the scale parameter in meshVTKloader is used with the bad encoding (0,001 written in place of 0.001), no error or warning is given, but the simulation doesn't work in batch mode.

**Comment by damienmarchal** [comment] 2017-01-25 20:22
Hi Guillaume,

After a quick look in the mesVTKLoader class you are totally right there is bug theres. This is related to the fact the that the VTKLoader is parsing the "scale" argumente using atoi/atof. These functions depends on the LC_LANG/LANG environment variables. 

Using 0,001 is not valid but does not generate an error.
We should fix that.

As this is code that I'm cleaning on I can probably fix that unless someone else want to do that.

**Comment by JeremieA** [comment] 2017-02-22 11:07
We lost more than a week of work recently, because for years in Sofa during initialization the LC_LANG/LANG variables were forced to the safe and sane "C" value, but it was removed during a "refactoring" (I can look up the id of the commit if that is useful). Since then, you have to expect bugs like this (particularly in closed-source haptic drivers...). I would prefer that we go back to this strategy, instead of finding and fixing all those bugs (some of which we can't fix anyway). The alternative is to ban all use of `atoi/atof/printf/scanf/iostream/...` :(

**Comment by damienmarchal** [comment] 2017-02-22 13:17
@JeremieA Same starting point, loosing time to understand what is wrong, but with a slightly different conclusion. 

I fully agree that the locale have to be set globally to each application calling sofa  to correctly parse number. 

But the real problem is caused by the fact that in Sofa there is places where we convert string to number while silently ignoring when something is wrong (or don't event detect something goes wrong as when using aoi/atoif) . 

Silently ignoring blatantly invalid user inputs sounds like a terrible behavior I think we should give time to eradicate this kind of code (and atoi/atof/scanf are definitely the first place I would look for).

**Comment by maxime-tournier** [comment] 2017-03-06 16:29
Instead of setting environment variables, we could call [imbue](http://en.cppreference.com/w/cpp/io/basic_ios/imbue) on input streams prior to parsing?

**Comment by damienmarchal** [comment] 2017-03-14 13:21
I think the initial issue is 'done' so we can close it. 

Further discussion should be done in a different issue titled: "Clarifying and Improving the way we handle LOCAL changes in Sofa"

**Closed as completed by damienmarchal** 2017-03-14 13:21 UTC
Labels: issue: bug (major)
