### ISSUE TITLE
[SofaGui] No GUI available on Ubuntu

### ISSUE THREAD

**Issue by dessteph** [sofa-framework/sofa#3006] opened 2022-06-03 13:39 UTC
Since the 05/06, there are no GUI available on Ubuntu on the master branch.

**Comment by epernod** [comment] 2022-06-03 19:05
What do you mean by available? no option on the cmake? not compiling?

**Comment by dessteph** [comment] 2022-06-04 11:44
The Cmake option is set on true, it compile but when I run runSofa there is no gui available. Even when I consult the help with runSofa -h there is only the batch in the list of GUI.

**Comment by alxbilger** [comment] 2022-06-04 12:47
@dessteph thanks for reporting the issue. It should be fixed in #3007. Can you try it and confirm the issue is fixed?

**Closed as completed** 2022-06-04 14:18 UTC
Labels: issue: bug (major)
