### ISSUE TITLE
Multithread Unit test falling

### ISSUE THREAD

**Issue by bakpaul** [sofa-framework/sofa#4323] opened 2023-11-29 15:08 UTC
The unit test `ParallelImplementationsRegistry_test` is failing for CGLinearSolver, stating that it has no creator although it is clear that such a component has one.

**Comment by alxbilger** [comment] 2023-11-29 15:33
Isn't it fixed by https://github.com/sofa-framework/sofa/pull/4307 ?

**Comment by fredroy** [comment] 2023-12-01 04:56
> Isn't it fixed by #4307 ?

Actually this error started to appear with this PR #4307 apparently (it was not noticed while PR reviewing 🙊)

**Comment by alxbilger** [comment] 2023-12-18 11:07
Does this test still fail? I have tested and cannot reproduce it. And I did not do anything to fix it.

**Closed as completed** 2023-12-19 05:40 UTC
Labels: issue: bug (minor)
